name: Publish package to GitHub package registry

on:
  push:
    branches:
      - package
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci

  version-increase:
    needs: install-dependencies
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[patch]') || contains(github.event.head_commit.message, '[minor]') || contains(github.event.head_commit.message, '[major]')
    env:
      PATCH: ${{ contains(github.event.head_commit.message, '[patch]') }}
      MINOR: ${{ contains(github.event.head_commit.message, '[minor]') }}
      MAJOR: ${{ contains(github.event.head_commit.message, '[major]') }}
    defaults:
      run:
        working-directory: dist/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm version patch
        if: ${{ env.PATCH == 'true' }}
      - run: npm version minor
        if: ${{ env.MINOR == 'true' }}
      - run: npm version major
        if: ${{ env.MAJOR == 'true' }}
      - run: |
          cat package.json
          git config user.name 
          git config user.email


  publish-gpr:
    needs: version-increase
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: ls -la
      - run: npm run generate-styles
      - run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo '@cbechstein-digital:registry=https://npm.pkg.github.com' >> .npmrc
          echo 'always-auth=true' >> .npmrc
        working-directory: dist/web
      - run: npm publish
        working-directory: dist/web